import Foundation

/// One actionable observation about agent behavior patterns. Generated by
/// `HistoryAnalyzer` from `history.json` and persisted to `history_analysis.json`.
struct HistoryInsight: Codable, Identifiable, Equatable {
    let id: UUID
    let kind: Kind
    let severity: Severity
    let title: String
    let detail: String
    /// IDs of the history entries that triggered this insight (for drill-down).
    let evidenceIds: [UUID]
    let occurrences: Int
    let firstSeen: Date
    let lastSeen: Date

    enum Kind: String, Codable, CaseIterable {
        case promiseWithoutCommand   // explanation in future tense + 0 commands
        case truncatedReply          // summary mentions truncation / "listagem cortada"
        case missingContext          // "não tenho", "não consigo identificar" with 0 commands
        case repeatedFailure         // same command failing across turns
        case longConversation        // > N rounds for a single user request
        case toolMissing             // "command not found" pattern
        case planFollowupGap         // commands ran but summary says "ainda não foi feito"

        var label: String {
            switch self {
            case .promiseWithoutCommand: return "Promessa sem execução"
            case .truncatedReply:        return "Resposta truncada"
            case .missingContext:        return "Perda de contexto"
            case .repeatedFailure:       return "Falha repetida"
            case .longConversation:      return "Conversa longa demais"
            case .toolMissing:           return "Ferramenta ausente"
            case .planFollowupGap:       return "Plan executado mas summary nega"
            }
        }

        var icon: String {
            switch self {
            case .promiseWithoutCommand: return "clock.badge.exclamationmark"
            case .truncatedReply:        return "scissors"
            case .missingContext:        return "questionmark.bubble"
            case .repeatedFailure:       return "arrow.clockwise.circle"
            case .longConversation:      return "tortoise"
            case .toolMissing:           return "wrench.and.screwdriver"
            case .planFollowupGap:       return "exclamationmark.triangle"
            }
        }
    }

    enum Severity: String, Codable, Comparable {
        case info
        case warning
        case critical

        private var rank: Int {
            switch self {
            case .info: return 0
            case .warning: return 1
            case .critical: return 2
            }
        }

        static func < (lhs: Severity, rhs: Severity) -> Bool { lhs.rank < rhs.rank }

        var color: String {
            switch self {
            case .info:     return "blue"
            case .warning:  return "orange"
            case .critical: return "red"
            }
        }

        var label: String {
            switch self {
            case .info:     return "Info"
            case .warning:  return "Atenção"
            case .critical: return "Crítico"
            }
        }
    }
}

/// Aggregate report produced by analyzing the history file. Persisted next to
/// the history itself so the UI can show it instantly without re-running the
/// analysis on every open.
struct HistoryAnalysisReport: Codable {
    let generatedAt: Date
    let totalEntries: Int
    let analyzedEntries: Int
    let insights: [HistoryInsight]
    /// `entryId → list of insight kinds`, so the UI can mark history rows.
    let flaggedEntries: [String: [String]]
    let summary: HealthSummary

    struct HealthSummary: Codable {
        let successRate: Double          // 0…1
        let avgCommandsPerTurn: Double
        let promiseRate: Double          // 0-cmd promise / total
        let truncationRate: Double
        let topProblemKind: String?
    }

    static let empty = HistoryAnalysisReport(
        generatedAt: .distantPast,
        totalEntries: 0,
        analyzedEntries: 0,
        insights: [],
        flaggedEntries: [:],
        summary: HealthSummary(
            successRate: 0,
            avgCommandsPerTurn: 0,
            promiseRate: 0,
            truncationRate: 0,
            topProblemKind: nil
        )
    )

    var isEmpty: Bool { analyzedEntries == 0 }
}
